# Artifacts Root 
artifacts_root: artifacts

# Data Ingestion
data_ingestion:
  root_path: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion

# Data Validation
